Change: Fail the update docs job earlier when BaNaNaS had no updates.
Currently BaNaNaS does not allow for users to upload new content /
updates, so until this bug is fixed no updates in this repo shall
appear.

diff --git a/.github/workflows/update_docs.yml b/.github/workflows/update_docs.yml
--- a/.github/workflows/update_docs.yml
+++ b/.github/workflows/update_docs.yml
@@ -20,7 +20,15 @@ jobs:
         python-version: 3.x
 
     - name: Download BaNaNaS
-      run: git clone https://github.com/OpenTTD/BaNaNaS.git bananas
+      run: |
+        git clone https://github.com/OpenTTD/BaNaNaS.git bananas
+        cd bananas
+        if [ "$(git rev-parse HEAD)" = "$(cat ../last_bananas_commit)" ]; then
+          echo "The documentation is up-to-date. :)"
+          echo 'Exiting with "No data available" error code.'
+          exit 61
+        fi
+        cd ..
 
     - name: Install dependencies
       run: |
